### ISSUE TITLE
Configuring TigerVNC User - Ubuntu

### ISSUE THREAD

**Issue by ammazzetto2** [techcraftco/rpi-usb-gadget#11]
I am having dome difficulties configuring the TigerVNC user. 

After `sudo vim /etc/tigervnc/vncserver.users` and adding the pi password I land on the same screen as in the video (Ubuntu Desktop on iPad) but  in the TigerVNC User assignment, when I add

`:2=pi`

I get the following error:

E488: Trailing characters: i

Any suggestions?

**Comment by robharrop** [comment]
Where is that error being reported? Is it in a specific log file or does it pop up on screen?

**Comment by ammazzetto2** [comment]
It appears in the screen, as a red box at the bottom. When I type the `:2=pi` it doesn't go to the same spot as the video - the text appear at the bottom of the screen.

Should I do this part while connected to the iPad? I connected the pi to a external monitor/keyboard to install Ubuntu and configure TigerVNC. 

If yes, how did you do it? I know you mentioned using BlinkShell to connect via SSH, but I couldn't figure it out how to - sorry, beginner here :)

**Comment by ammazzetto2** [comment]
Ok, I think I managed to do it and it is working fine on the iPad...it took some time googling and watching other videos from you, but it is working now.

Thanks!

**Comment by robharrop** [comment]
Great! I realise from your description that I completely glossed over the fact that I was using the vim editor which has keybindings that are not intuitive!
