### ISSUE TITLE
Ubuntu Server arm64: Unable to connect to internet on Pi when connected to iPad Pro

### ISSUE THREAD

**Issue by thekeith** [techcraftco/rpi-usb-gadget#12]
Based on previous videos it looks like you're able to connect to the internet on the Pi through the usb-C connection of the iPad Pro. While I have been able to set up the Ubuntu 22.04 arm64 install without issue, the Pi is unable to use the iPad Pro for internet when solely connected to it.

I've tested a few solutions from Ben Hardill and others to no avail. System works as expected otherwise, but would be great to have internet shared from the iPad for remote sessions.

**Comment by robharrop** [comment]
Sharing the iPad connection doesn't work in this setup. It will work in a USB tether setup, but only on cellular iPads. I have a video showing this here: https://youtu.be/cD3JN8BHosI

**Comment by thekeith** [comment]
Thanks - will try that.
