### ISSUE TITLE
Copy a Raspberry Pi image with the iPad 

### ISSUE THREAD

**Issue by ralf-krause** [techcraftco/rpi-usb-gadget#13]
I found your videos about the iPad Pro and the Raspberry Pi. Great work!

In the video [https://www.youtube.com/watch?v=SPSlyqo5Q2Q at 4:51](https://www.youtube.com/watch?v=SPSlyqo5Q2Q&t=291s) you talk about installing the Raspberry Pi from the iPad Pro. Yes, it works! Take the NOOBS setup and copy it on a microSD card. 

There is a thread about this in the MoodleBox forum https://discuss.moodlebox.net/d/333-download-moodlebox-image-directly-to-an-external-sd-card-on-an-android/8 where somebody asked about copying an image with a Android smartphone. I tested the app "RasPi Card Imager" and found that it is using NOOBS. And I tried to do the same with my iPad Air 4. Please read the thread in the MoodleBox forum about the results.  :-)

Best regards,
Ralf

**Comment by robharrop** [comment]
Thanks @ralf-krause - that's really useful. I'm going to give that a go. I completely forgot about NOOBS, it's been years since I used it!
