### ISSUE TITLE
Pi Hole setup broken when using custom image

### ISSUE THREAD

**Issue by ibmgeniuz** [techcraftco/rpi-usb-gadget#14]
Hello @robharrop thanks for you wonderful tutorials and the custom images. Recently I have been trying to install pi-hole using your YouTube tutorials and realised that when using your custom images (even fresh install), the installation does not complete. I'm not sure what I need to change to make it work. I have tried all the custom images including desktop version and all give same result. I used the quick install script. It's very convenient using your custom images with the out of the box usb-c to iPad connection. 

System: Raspberry Pi 4 8gb
Distro: Pi OS Lite/Desktop, Ubuntu Server
Storage: SD Card 32gb

Steps to reproduce
1. Install custom image on SD Card
2. Run `sudo apt update` and `sudo apt upgrade` 
3. Run `curl -sSL https://install.pi-hole.net | bash`
4. Follow all prompts choosing defaults (I have static IP setup via router)

Also I can verify that using the Pi OS Lite from raspberry.org worked and pi-hole was successfully installed. I assume there may be some port conflicts with your custom config.

**Comment by robharrop** [comment]
I've never tried the Pihole setup with the custom images but I can fully imagine they won't work. I think a better setup for using Pihole alongside the iPad might be to use the simpler zeroconf setup for Pi<->iPad communications. 

That setup is shown in this video: https://youtu.be/3UPaI4Hp66Y
