### ISSUE TITLE
Debian instead of Raspbian listed in: /etc/os-release

### ISSUE THREAD

**Issue by MightyAx** [techcraftco/rpi-usb-gadget#3]
I used the arm64 desktop image of the [0.2 release](https://github.com/techcraftco/rpi-usb-gadget/releases/tag/v0.2), and followed the instructions to use the raspberry pi imager.

This results with an OS that identifies as Debian instead of Raspbian:
`cat /etc/os-release `
results with the following, non-raspbian  entry:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I’m fairly new to this so don’t know how much of an impact it is, but I can’t get sonic pi to startup since it required a detection of Raspbian to deploy some specific fixes.

**Comment by robharrop** [comment]
This is the same behaviour as Raspberry Pi OS out-of-the-box. I'm not sure when this changed, but I just booted up a plain RaspiOS image (the one that v0.2 is based on) and I get the exact same output for `/etc/os-release`.

**Comment by robharrop** [comment]
I'm going to close this because I think this is working as it should - at least compared to stock RPi OS. Feel free to reopen if it turns out I'm mistaken!

**Comment by MightyAx** [comment]
No worries, thanks for checking!
