### ISSUE TITLE
Default password not working

### ISSUE THREAD

**Issue by d-johnston-fugro** [techcraftco/rpi-usb-gadget#4]
I flashed the latest image to my Pi today and the default login of

Username: pi
Password: raspberry

Is not working, I’ve tried from several different computers without luck so I don’t think it’s an issue with keyboard localisation or accidental Caps Lock. I also looked through the Packer config and there doesn’t appear to be anything that would alter the login details from the base image.

However, on the Raspberry Pi website it seems like recommended process is now to setup the password using the boot loader, perhaps the newer images don’t have the same default password?

**Comment by robharrop** [comment]
The latest v0.2 images are using the same password policy as the corresponding Raspberry Pi OS images, so there's no longer a default password. 

You can create a config file to control the user on boot image: https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-a-user

You can also cerate that file using Raspberry Pi Imager during the burning process. I filmed a video showing that here: https://www.youtube.com/watch?v=dUeQUCF6KPc&t=313s

**Comment by d-johnston-fugro** [comment]
Thanks for the help! I'm not very familiar with the Raspberry Pi OS so I was pulling my hair out trying to get this to work. I haven't got a micro HDMI cable so I was relying on the ability to SSH into the machine over USB C.
